# Generated by Django 4.2.2 on 2023-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=5000)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='staff_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=5000)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='user_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=5000)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='useraccount_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('firstname', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('accounttype', models.CharField(max_length=500)),
            ],
        ),
    ]
