# Generated by Django 4.2.2 on 2023-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_tbl',
            old_name='password',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='seller_tbl',
            name='password',
        ),
        migrations.AddField(
            model_name='staff_tbl',
            name='designation',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_tbl',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='staff_tbl',
            name='photo',
            field=models.CharField(max_length=500),
        ),
    ]
