# Generated by Django 4.2.2 on 2023-09-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0002_rename_password_staff_tbl_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_tbl',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
