# Generated by Django 4.2.2 on 2023-09-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0003_alter_staff_tbl_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount_tbl',
            name='phone',
        ),
    ]
