# Generated by Django 4.2.2 on 2023-10-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0005_produt_tbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produt_tbl',
        ),
    ]
