# Generated by Django 4.2.2 on 2023-10-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0007_produt_tbl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produt_tbl',
            new_name='product_tbl',
        ),
    ]
