# Generated by Django 4.2.2 on 2023-10-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0008_rename_produt_tbl_product_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('productname', models.CharField(max_length=500)),
                ('quantity', models.CharField(max_length=500)),
            ],
        ),
    ]
