# Generated by Django 4.2.2 on 2023-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0009_cart_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tbl',
            old_name='name',
            new_name='batetrystatus',
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='brand',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='price',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='satus',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='sellername',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='username',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='brandname',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='modelname',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='sellername',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
