# Generated by Django 4.0.4 on 2023-10-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0010_rename_name_product_tbl_batetrystatus_cart_tbl_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_tbl',
            name='totalAmount',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
