# Generated by Django 4.0.4 on 2023-10-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileshopapp', '0012_alter_cart_tbl_price_alter_cart_tbl_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tbl',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart_tbl',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
